name:                langparser
version:             0.1.0.0
github:              "arikai/langparser"
license:             BSD3
author:              "Yaroslav Rogov"
maintainer:          "rogovyaroslav@gmail.com"
copyright:           "2020 Yaroslav Rogov"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/arikai/langparser#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- parsec >= 3.1 && < 4
- mtl
- here

library:
  source-dirs: src

executables:
  langparser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - langparser

tests:
  langparser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - langparser
